1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [6]:
import numpy as np
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [12]:
import numpy as np
a = np.random.randint(1, 10, size=(5, 5))
print(a)

[[6 2 4 5 2]
 [1 9 8 9 9]
 [2 7 1 3 7]
 [4 4 5 2 3]
 [8 5 2 2 1]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [13]:
import numpy as np
a = np.random.random((4, 4))
print(a)

[[0.22461125 0.51047747 0.92116632 0.79772831]
 [0.3203596  0.2964723  0.40642392 0.57857646]
 [0.24138925 0.72308611 0.36973179 0.75759566]
 [0.11575588 0.54096288 0.24724952 0.05141063]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні

In [16]:
import numpy as np
a = np.random.randint(1, 10, size=5)
b = np.random.randint(1, 10, size=5)
print(a + b)
print(a - b)
print(a * b)

[11  7  6  3 13]
[-5 -3 -4  1 -5]
[24 10  5  2 36]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.


In [17]:
import numpy as np
a = np.random.randint(1, 10, size=7)
b = np.random.randint(1, 10, size=7)
print(a.dot(b))

184


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [22]:
import numpy as np
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 3))
print(a.dot(b))

[[13 25 29]
 [19 45 17]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [32]:
import numpy as np
a = np.random.randint(1, 10, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0.10309278 -0.17525773  0.11340206]
 [-0.26804124 -0.1443299   0.50515464]
 [ 0.15463918  0.2371134  -0.32989691]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [29]:
import numpy as np
a = np.random.random(size=(4, 4))
print(a)
print()
print(a.T)

[[0.9363529  0.86163939 0.21821751 0.63559411]
 [0.51671564 0.88979218 0.12396351 0.30203817]
 [0.35883695 0.36500169 0.94869867 0.84714323]
 [0.71250339 0.27258067 0.98461123 0.17099198]]

[[0.9363529  0.51671564 0.35883695 0.71250339]
 [0.86163939 0.88979218 0.36500169 0.27258067]
 [0.21821751 0.12396351 0.94869867 0.98461123]
 [0.63559411 0.30203817 0.84714323 0.17099198]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.


In [33]:
import numpy as np
a = np.random.randint(1, 10, size=(3, 4))
b = np.random.randint(1, 10, size=4)
print(a * b)

[[42  7 32 45]
 [18  5 56 72]
 [30  3 56 45]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [34]:
import numpy as np
a = np.random.random(size=(3, 4))
b = np.random.random(size=4)
print(a * b)

[[0.00144268 0.58181325 0.27508846 0.20959422]
 [0.01128367 0.02229427 0.21389939 0.02026852]
 [0.00363427 0.65674711 0.21091513 0.24398102]]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [35]:
import numpy as np
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 2))
print(a * b)

[[ 5 25]
 [54 21]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [37]:
import numpy as np
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 2))
print(a.dot(b))

[[31 80]
 [25 62]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [39]:
import numpy as np
a = np.random.randint(1, 100, size=(5, 5))
print(a.sum())

1172


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [40]:
import numpy as np
a = np.random.randint(1, 10, size=(4, 4))
b = np.random.randint(1, 10, size=(4, 4))
print(a - b)

[[-7  0 -4  2]
 [ 4  4 -4 -4]
 [ 1 -1 -8  3]
 [-2  8  5  5]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [44]:
import numpy as np
a = np.random.random(size=(3, 3))
b = np.array([i.sum() for i in a])
print(b)

[1.96918731 2.04765554 1.25908446]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [45]:
import numpy as np
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]])

b = np.array([j**2 for j in (i for i in a)])
print(b)

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [52]:
import numpy as np
a = np.random.randint(1, 50, size=4)
b = np.array([i**0.5 for i in a])
print(a)
print(b)

[45 43 36 23]
[6.70820393 6.55743852 6.         4.79583152]
